apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: Z2hwX0RTbU5uRFF1QnRhUFpkVHNrSzJURWQzU1pxTkVKcDMyS2MxNQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  imagePullSecrets:
    - name: ghcr-secret
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/kavitate172/helloworld:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: helloworld
