apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ICAgewogICAgICJhdXRocyI6IHsKICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAiYXV0aCI6ICJaMmh3WDBSVGJVNXVSRkYxUW5SaFVGcGtWSE5yU3pKVVJXUXpVMXB4VGtWS2NETXlTMk14TlFvPSIKICAgICAgIH0KICAgICB9CiAgIH0KICAgCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: helloworld
        image: ghcr.io/kavitate172/helloworld:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: helloworld
