name: Build and Deploy to k3s

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.K3S_KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          # Fix server URL if needed (uncomment if your kubeconfig points to localhost)
          # sed -i 's/server: .*/server: https:\/\/35.165.238.50:6443/' kubeconfig.yaml
          cat kubeconfig.yaml > ~/.kube/config

      # Deploy application
      - name: Deploy to cluster
        run: |
          kubectl config view  --insecure-skip-tls-verify # Debug: Show final config
          kubectl cluster-info --insecure-skip-tls-verify # Debug: Verify cluster connection
          
          # Apply manifests with both insecure and validation flags
          kubectl apply -f k8s/ --insecure-skip-tls-verify --validate=false
          kubectl rollout status deployment/helloworld --insecure-skip-tls-verify


